image: rust
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
    - $CARGO_HOME

stages:
    - check
    - deploy

before_script:
  - export PATH="$PATH:$CARGO_HOME/bin"
  - cargo install mdbook mdbook-infisearch

build:
  stage: check
  script:
    - mdbook build
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

pages:
  stage: deploy
  script:
    - mdbook build -d public
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - public/html
