[book]
authors = ["huangjj27"]
language = "zh"
multilingual = false
src = "src"
title = "huangjj27 的技术博客"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
no-section-label = true
git-repository-url = "https://gitlab.com/huangjj27/huangjj27.gitlab.io"
git-repository-icon = "fa-gitlab"

[output.html.print]
enable = false

[output.html.fold]
enable = false
level = 0

[output.html.playground]
editable = false
copy-js = true
line-numbers = false

[output.html.search]
enable = false      # wait for a usable chinese searching plugin!
