# ANCHOR: show
# Cargo.toml
[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
rand = "0.3.14"
# ANCHOR_END: show

[[bin]]
name = "guess"
path = "./main.rs"
