name: build

on:
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: cargo install mdbook
    - name: Build
      run: mdbook build

  cache:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2s
        with:
          path: |
            ~/.cargo
