name: build

on:
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      uses: actions-rs/install@v0.1
      with:
        crate: mdbook
        version: latest
        use-tool-cache: true
    - name: Build
      run: mdbook build
