name: Check if it can be published

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: cargo install mdbook
    # - uses: actions/cache@v2
    #   with:
    #     path: ~/.cargo
    - name: Build
      run: mdbook build

  # pages:
  #   needs: [build]
