name: build

on:
  push: dev
  pull_request: dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      uses: actions-rs/install@v0.1
      with:
        crate: mdbook
        version: latest
        use-tool-cache: true
    - name: Build
      run: mdbook build

jobs:
  deploy:
    needs: [build]
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
        publish_branch: master
