name: Mdbook Pages

on:
  push:
    branches: dev
  pull_request:
    branches: dev

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      uses: actions-rs/install@v0.1
      with:
        crate: mdbook
        version: latest
        use-tool-cache: true
    - name: Build mdbook
      run: mdbook build && pwd
    - name: Cache artifact
      uses: actions/upload-artifact@v1
      with:
        name: book
        path: ./book

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get artifact
      uses: actions/download-artifact@v1
      with:
        name: book
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./book
        publish_branch: master
        allow_empty_commit: true
        user_name: "huangjj27"
        user_email: "huangjj.27@qq.com"
        force_orphan: true
